services:
  backend:
    command: npm run dev
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
