pipeline {
  agent any

  stages {

    stage('Checkout Code') {
      steps {
        git branch: 'PROD',
            url: 'https://github.com/mahammad-devarakonda/Bondly.git',
            credentialsId: 'github-creds'
      }
    }

    stage('Build Docker Images') {
      steps {
        sh 'docker compose build'
      }
    }

    stage('Deploy Application') {
      steps {
        sh '''
          docker compose down
          docker compose up -d
        '''
      }
    }
  }

  post {
    success {
      echo '✅ Bondly deployed successfully'
    }
    failure {
      echo '❌ Deployment failed'
    }
  }
}
