pipeline {
  agent any

  tools {
    nodejs 'Node18'
  }

  stages {

    stage('Checkout Code') {
      steps {
        git branch: 'PROD',
            url: 'https://github.com/mahammad-devarakonda/Bondly.git',
            credentialsId: 'github-creds'
      }
    }

    stage('Backend Install') {
      steps {
        dir('server') {
          sh 'npm install'
        }
      }
    }

    stage('Frontend Build') {
      steps {
        dir('client') {
          sh '''
            npm install
            npm run build
          '''
        }
      }
    }

    stage('Deploy Backend code') {
      steps {
        dir('server') {
          sh '''
            pm2 stop bondly-backend || true
            pm2 start index.js --name bondly-backend
            pm2 save
          '''
        }
      }
    }

    stage('Deploy Frontend code') {
      steps {
        sh '''
          sudo rm -rf /var/www/html/*
          sudo cp -r client/build/* /var/www/html/
        '''
      }
    }
  }
}
